// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ActivitiListener
    {
        /// <summary>
        /// Initializes a new instance of the ActivitiListener class.
        /// </summary>
        public ActivitiListener()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ActivitiListener class.
        /// </summary>
        public ActivitiListener(string id = default(string), int? xmlRowNumber = default(int?), int? xmlColumnNumber = default(int?), IDictionary<string, IList<ExtensionElement>> extensionElements = default(IDictionary<string, IList<ExtensionElement>>), IDictionary<string, IList<ExtensionAttribute>> attributes = default(IDictionary<string, IList<ExtensionAttribute>>), string eventProperty = default(string), string implementationType = default(string), string implementation = default(string), IList<FieldExtension> fieldExtensions = default(IList<FieldExtension>), string onTransaction = default(string), string customPropertiesResolverImplementationType = default(string), string customPropertiesResolverImplementation = default(string))
        {
            Id = id;
            XmlRowNumber = xmlRowNumber;
            XmlColumnNumber = xmlColumnNumber;
            ExtensionElements = extensionElements;
            Attributes = attributes;
            EventProperty = eventProperty;
            ImplementationType = implementationType;
            Implementation = implementation;
            FieldExtensions = fieldExtensions;
            OnTransaction = onTransaction;
            CustomPropertiesResolverImplementationType = customPropertiesResolverImplementationType;
            CustomPropertiesResolverImplementation = customPropertiesResolverImplementation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "xmlRowNumber")]
        public int? XmlRowNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "xmlColumnNumber")]
        public int? XmlColumnNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "extensionElements")]
        public IDictionary<string, IList<ExtensionElement>> ExtensionElements { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "attributes")]
        public IDictionary<string, IList<ExtensionAttribute>> Attributes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "event")]
        public string EventProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "implementationType")]
        public string ImplementationType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "implementation")]
        public string Implementation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fieldExtensions")]
        public IList<FieldExtension> FieldExtensions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "onTransaction")]
        public string OnTransaction { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customPropertiesResolverImplementationType")]
        public string CustomPropertiesResolverImplementationType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customPropertiesResolverImplementation")]
        public string CustomPropertiesResolverImplementation { get; set; }

    }
}
