// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DeploymentResourceResponse
    {
        /// <summary>
        /// Initializes a new instance of the DeploymentResourceResponse class.
        /// </summary>
        public DeploymentResourceResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DeploymentResourceResponse class.
        /// </summary>
        /// <param name="mediaType">Contains the media-type the resource has.
        /// This is resolved using a (pluggable) MediaTypeResolver and
        /// contains, by default, a limited number of mime-type
        /// mappings.</param>
        /// <param name="type">Type of resource. Possible values include:
        /// 'resource', 'processDefinition', 'processImage'</param>
        public DeploymentResourceResponse(string id = default(string), string url = default(string), string contentUrl = default(string), string mediaType = default(string), string type = default(string))
        {
            Id = id;
            Url = url;
            ContentUrl = contentUrl;
            MediaType = mediaType;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contentUrl")]
        public string ContentUrl { get; set; }

        /// <summary>
        /// Gets or sets contains the media-type the resource has. This is
        /// resolved using a (pluggable) MediaTypeResolver and contains, by
        /// default, a limited number of mime-type mappings.
        /// </summary>
        [JsonProperty(PropertyName = "mediaType")]
        public string MediaType { get; set; }

        /// <summary>
        /// Gets or sets type of resource. Possible values include: 'resource',
        /// 'processDefinition', 'processImage'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

    }
}
