// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class EventResponse
    {
        /// <summary>
        /// Initializes a new instance of the EventResponse class.
        /// </summary>
        public EventResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EventResponse class.
        /// </summary>
        public EventResponse(string url = default(string), string id = default(string), string action = default(string), string userId = default(string), System.DateTime? time = default(System.DateTime?), string taskUrl = default(string), string processInstanceUrl = default(string), IList<string> message = default(IList<string>))
        {
            Url = url;
            Id = id;
            Action = action;
            UserId = userId;
            Time = time;
            TaskUrl = taskUrl;
            ProcessInstanceUrl = processInstanceUrl;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "action")]
        public string Action { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "time")]
        public System.DateTime? Time { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "taskUrl")]
        public string TaskUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processInstanceUrl")]
        public string ProcessInstanceUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public IList<string> Message { get; set; }

    }
}
