// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ExecutionResponse
    {
        /// <summary>
        /// Initializes a new instance of the ExecutionResponse class.
        /// </summary>
        public ExecutionResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExecutionResponse class.
        /// </summary>
        public ExecutionResponse(string id = default(string), string url = default(string), string parentId = default(string), string parentUrl = default(string), string superExecutionId = default(string), string superExecutionUrl = default(string), string processInstanceId = default(string), string processInstanceUrl = default(string), bool? suspended = default(bool?), string activityId = default(string), string tenantId = default(string))
        {
            Id = id;
            Url = url;
            ParentId = parentId;
            ParentUrl = parentUrl;
            SuperExecutionId = superExecutionId;
            SuperExecutionUrl = superExecutionUrl;
            ProcessInstanceId = processInstanceId;
            ProcessInstanceUrl = processInstanceUrl;
            Suspended = suspended;
            ActivityId = activityId;
            TenantId = tenantId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentId")]
        public string ParentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentUrl")]
        public string ParentUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "superExecutionId")]
        public string SuperExecutionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "superExecutionUrl")]
        public string SuperExecutionUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processInstanceId")]
        public string ProcessInstanceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processInstanceUrl")]
        public string ProcessInstanceUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "suspended")]
        public bool? Suspended { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "activityId")]
        public string ActivityId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public string TenantId { get; set; }

    }
}
