// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GraphicInfo
    {
        /// <summary>
        /// Initializes a new instance of the GraphicInfo class.
        /// </summary>
        public GraphicInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GraphicInfo class.
        /// </summary>
        public GraphicInfo(double? x = default(double?), double? y = default(double?), double? height = default(double?), double? width = default(double?), BaseElement element = default(BaseElement), bool? expanded = default(bool?), int? xmlRowNumber = default(int?), int? xmlColumnNumber = default(int?))
        {
            X = x;
            Y = y;
            Height = height;
            Width = width;
            Element = element;
            Expanded = expanded;
            XmlRowNumber = xmlRowNumber;
            XmlColumnNumber = xmlColumnNumber;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "x")]
        public double? X { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "y")]
        public double? Y { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "height")]
        public double? Height { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "width")]
        public double? Width { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "element")]
        public BaseElement Element { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "expanded")]
        public bool? Expanded { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "xmlRowNumber")]
        public int? XmlRowNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "xmlColumnNumber")]
        public int? XmlColumnNumber { get; set; }

    }
}
