// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GroupRequest
    {
        /// <summary>
        /// Initializes a new instance of the GroupRequest class.
        /// </summary>
        public GroupRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GroupRequest class.
        /// </summary>
        public GroupRequest(string id = default(string), string url = default(string), string name = default(string), string type = default(string), bool? nameChanged = default(bool?), bool? typeChanged = default(bool?))
        {
            Id = id;
            Url = url;
            Name = name;
            Type = type;
            NameChanged = nameChanged;
            TypeChanged = typeChanged;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nameChanged")]
        public bool? NameChanged { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "typeChanged")]
        public bool? TypeChanged { get; set; }

    }
}
