// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class HistoricVariableInstanceQueryRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// HistoricVariableInstanceQueryRequest class.
        /// </summary>
        public HistoricVariableInstanceQueryRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// HistoricVariableInstanceQueryRequest class.
        /// </summary>
        public HistoricVariableInstanceQueryRequest(bool? excludeTaskVariables = default(bool?), string taskId = default(string), string executionId = default(string), string processInstanceId = default(string), string variableName = default(string), string variableNameLike = default(string), IList<QueryVariable> variables = default(IList<QueryVariable>))
        {
            ExcludeTaskVariables = excludeTaskVariables;
            TaskId = taskId;
            ExecutionId = executionId;
            ProcessInstanceId = processInstanceId;
            VariableName = variableName;
            VariableNameLike = variableNameLike;
            Variables = variables;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "excludeTaskVariables")]
        public bool? ExcludeTaskVariables { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "taskId")]
        public string TaskId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "executionId")]
        public string ExecutionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processInstanceId")]
        public string ProcessInstanceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "variableName")]
        public string VariableName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "variableNameLike")]
        public string VariableNameLike { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "variables")]
        public IList<QueryVariable> Variables { get; set; }

    }
}
