// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class HistoricProcessInstanceQueryRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// HistoricProcessInstanceQueryRequest class.
        /// </summary>
        public HistoricProcessInstanceQueryRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// HistoricProcessInstanceQueryRequest class.
        /// </summary>
        public HistoricProcessInstanceQueryRequest(int? start = default(int?), int? size = default(int?), string sort = default(string), string order = default(string), string processInstanceId = default(string), IList<string> processInstanceIds = default(IList<string>), string processBusinessKey = default(string), string processDefinitionId = default(string), string processDefinitionKey = default(string), string superProcessInstanceId = default(string), bool? excludeSubprocesses = default(bool?), bool? finished = default(bool?), string involvedUser = default(string), System.DateTime? finishedAfter = default(System.DateTime?), System.DateTime? finishedBefore = default(System.DateTime?), System.DateTime? startedAfter = default(System.DateTime?), System.DateTime? startedBefore = default(System.DateTime?), string startedBy = default(string), bool? includeProcessVariables = default(bool?), IList<QueryVariable> variables = default(IList<QueryVariable>), string tenantId = default(string), string tenantIdLike = default(string), bool? withoutTenantId = default(bool?))
        {
            Start = start;
            Size = size;
            Sort = sort;
            Order = order;
            ProcessInstanceId = processInstanceId;
            ProcessInstanceIds = processInstanceIds;
            ProcessBusinessKey = processBusinessKey;
            ProcessDefinitionId = processDefinitionId;
            ProcessDefinitionKey = processDefinitionKey;
            SuperProcessInstanceId = superProcessInstanceId;
            ExcludeSubprocesses = excludeSubprocesses;
            Finished = finished;
            InvolvedUser = involvedUser;
            FinishedAfter = finishedAfter;
            FinishedBefore = finishedBefore;
            StartedAfter = startedAfter;
            StartedBefore = startedBefore;
            StartedBy = startedBy;
            IncludeProcessVariables = includeProcessVariables;
            Variables = variables;
            TenantId = tenantId;
            TenantIdLike = tenantIdLike;
            WithoutTenantId = withoutTenantId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start")]
        public int? Start { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "size")]
        public int? Size { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sort")]
        public string Sort { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "order")]
        public string Order { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processInstanceId")]
        public string ProcessInstanceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processInstanceIds")]
        public IList<string> ProcessInstanceIds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processBusinessKey")]
        public string ProcessBusinessKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processDefinitionId")]
        public string ProcessDefinitionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processDefinitionKey")]
        public string ProcessDefinitionKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "superProcessInstanceId")]
        public string SuperProcessInstanceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "excludeSubprocesses")]
        public bool? ExcludeSubprocesses { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "finished")]
        public bool? Finished { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "involvedUser")]
        public string InvolvedUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "finishedAfter")]
        public System.DateTime? FinishedAfter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "finishedBefore")]
        public System.DateTime? FinishedBefore { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startedAfter")]
        public System.DateTime? StartedAfter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startedBefore")]
        public System.DateTime? StartedBefore { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startedBy")]
        public string StartedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "includeProcessVariables")]
        public bool? IncludeProcessVariables { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "variables")]
        public IList<QueryVariable> Variables { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public string TenantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantIdLike")]
        public string TenantIdLike { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "withoutTenantId")]
        public bool? WithoutTenantId { get; set; }

    }
}
