// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class HistoricIdentityLinkResponse
    {
        /// <summary>
        /// Initializes a new instance of the HistoricIdentityLinkResponse
        /// class.
        /// </summary>
        public HistoricIdentityLinkResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HistoricIdentityLinkResponse
        /// class.
        /// </summary>
        public HistoricIdentityLinkResponse(string type = default(string), string userId = default(string), string groupId = default(string), string taskId = default(string), string taskUrl = default(string), string processInstanceId = default(string), string processInstanceUrl = default(string))
        {
            Type = type;
            UserId = userId;
            GroupId = groupId;
            TaskId = taskId;
            TaskUrl = taskUrl;
            ProcessInstanceId = processInstanceId;
            ProcessInstanceUrl = processInstanceUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "groupId")]
        public string GroupId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "taskId")]
        public string TaskId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "taskUrl")]
        public string TaskUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processInstanceId")]
        public string ProcessInstanceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processInstanceUrl")]
        public string ProcessInstanceUrl { get; set; }

    }
}
