// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class HistoricActivityInstanceQueryRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// HistoricActivityInstanceQueryRequest class.
        /// </summary>
        public HistoricActivityInstanceQueryRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// HistoricActivityInstanceQueryRequest class.
        /// </summary>
        public HistoricActivityInstanceQueryRequest(int? start = default(int?), int? size = default(int?), string sort = default(string), string order = default(string), string activityId = default(string), string activityInstanceId = default(string), string activityName = default(string), string activityType = default(string), string executionId = default(string), bool? finished = default(bool?), string taskAssignee = default(string), string processInstanceId = default(string), string processDefinitionId = default(string), string tenantId = default(string), string tenantIdLike = default(string), bool? withoutTenantId = default(bool?))
        {
            Start = start;
            Size = size;
            Sort = sort;
            Order = order;
            ActivityId = activityId;
            ActivityInstanceId = activityInstanceId;
            ActivityName = activityName;
            ActivityType = activityType;
            ExecutionId = executionId;
            Finished = finished;
            TaskAssignee = taskAssignee;
            ProcessInstanceId = processInstanceId;
            ProcessDefinitionId = processDefinitionId;
            TenantId = tenantId;
            TenantIdLike = tenantIdLike;
            WithoutTenantId = withoutTenantId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start")]
        public int? Start { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "size")]
        public int? Size { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sort")]
        public string Sort { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "order")]
        public string Order { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "activityId")]
        public string ActivityId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "activityInstanceId")]
        public string ActivityInstanceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "activityName")]
        public string ActivityName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "activityType")]
        public string ActivityType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "executionId")]
        public string ExecutionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "finished")]
        public bool? Finished { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "taskAssignee")]
        public string TaskAssignee { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processInstanceId")]
        public string ProcessInstanceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processDefinitionId")]
        public string ProcessDefinitionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public string TenantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantIdLike")]
        public string TenantIdLike { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "withoutTenantId")]
        public bool? WithoutTenantId { get; set; }

    }
}
