// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class IOSpecification
    {
        /// <summary>
        /// Initializes a new instance of the IOSpecification class.
        /// </summary>
        public IOSpecification()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IOSpecification class.
        /// </summary>
        public IOSpecification(string id = default(string), int? xmlRowNumber = default(int?), int? xmlColumnNumber = default(int?), IDictionary<string, IList<ExtensionElement>> extensionElements = default(IDictionary<string, IList<ExtensionElement>>), IDictionary<string, IList<ExtensionAttribute>> attributes = default(IDictionary<string, IList<ExtensionAttribute>>), IList<DataSpec> dataInputs = default(IList<DataSpec>), IList<DataSpec> dataOutputs = default(IList<DataSpec>), IList<string> dataInputRefs = default(IList<string>), IList<string> dataOutputRefs = default(IList<string>))
        {
            Id = id;
            XmlRowNumber = xmlRowNumber;
            XmlColumnNumber = xmlColumnNumber;
            ExtensionElements = extensionElements;
            Attributes = attributes;
            DataInputs = dataInputs;
            DataOutputs = dataOutputs;
            DataInputRefs = dataInputRefs;
            DataOutputRefs = dataOutputRefs;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "xmlRowNumber")]
        public int? XmlRowNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "xmlColumnNumber")]
        public int? XmlColumnNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "extensionElements")]
        public IDictionary<string, IList<ExtensionElement>> ExtensionElements { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "attributes")]
        public IDictionary<string, IList<ExtensionAttribute>> Attributes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataInputs")]
        public IList<DataSpec> DataInputs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataOutputs")]
        public IList<DataSpec> DataOutputs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataInputRefs")]
        public IList<string> DataInputRefs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataOutputRefs")]
        public IList<string> DataOutputRefs { get; set; }

    }
}
