// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class JobResponse
    {
        /// <summary>
        /// Initializes a new instance of the JobResponse class.
        /// </summary>
        public JobResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JobResponse class.
        /// </summary>
        public JobResponse(string id = default(string), string url = default(string), string processInstanceId = default(string), string processInstanceUrl = default(string), string processDefinitionId = default(string), string processDefinitionUrl = default(string), string executionId = default(string), string executionUrl = default(string), int? retries = default(int?), string exceptionMessage = default(string), System.DateTime? dueDate = default(System.DateTime?), string tenantId = default(string))
        {
            Id = id;
            Url = url;
            ProcessInstanceId = processInstanceId;
            ProcessInstanceUrl = processInstanceUrl;
            ProcessDefinitionId = processDefinitionId;
            ProcessDefinitionUrl = processDefinitionUrl;
            ExecutionId = executionId;
            ExecutionUrl = executionUrl;
            Retries = retries;
            ExceptionMessage = exceptionMessage;
            DueDate = dueDate;
            TenantId = tenantId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processInstanceId")]
        public string ProcessInstanceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processInstanceUrl")]
        public string ProcessInstanceUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processDefinitionId")]
        public string ProcessDefinitionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processDefinitionUrl")]
        public string ProcessDefinitionUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "executionId")]
        public string ExecutionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "executionUrl")]
        public string ExecutionUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "retries")]
        public int? Retries { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exceptionMessage")]
        public string ExceptionMessage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dueDate")]
        public System.DateTime? DueDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public string TenantId { get; set; }

    }
}
