// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MembershipResponse
    {
        /// <summary>
        /// Initializes a new instance of the MembershipResponse class.
        /// </summary>
        public MembershipResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MembershipResponse class.
        /// </summary>
        public MembershipResponse(string userId = default(string), string url = default(string), string groupId = default(string))
        {
            UserId = userId;
            Url = url;
            GroupId = groupId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "groupId")]
        public string GroupId { get; set; }

    }
}
