// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MembershipRequest
    {
        /// <summary>
        /// Initializes a new instance of the MembershipRequest class.
        /// </summary>
        public MembershipRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MembershipRequest class.
        /// </summary>
        public MembershipRequest(string userId = default(string))
        {
            UserId = userId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

    }
}
