// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ModelResponse
    {
        /// <summary>
        /// Initializes a new instance of the ModelResponse class.
        /// </summary>
        public ModelResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ModelResponse class.
        /// </summary>
        public ModelResponse(string name = default(string), string key = default(string), string category = default(string), int? version = default(int?), string metaInfo = default(string), string deploymentId = default(string), string tenantId = default(string), string id = default(string), string url = default(string), System.DateTime? createTime = default(System.DateTime?), System.DateTime? lastUpdateTime = default(System.DateTime?), string deploymentUrl = default(string), string sourceUrl = default(string), string sourceExtraUrl = default(string))
        {
            Name = name;
            Key = key;
            Category = category;
            Version = version;
            MetaInfo = metaInfo;
            DeploymentId = deploymentId;
            TenantId = tenantId;
            Id = id;
            Url = url;
            CreateTime = createTime;
            LastUpdateTime = lastUpdateTime;
            DeploymentUrl = deploymentUrl;
            SourceUrl = sourceUrl;
            SourceExtraUrl = sourceExtraUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public int? Version { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "metaInfo")]
        public string MetaInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deploymentId")]
        public string DeploymentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public string TenantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createTime")]
        public System.DateTime? CreateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastUpdateTime")]
        public System.DateTime? LastUpdateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deploymentUrl")]
        public string DeploymentUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sourceUrl")]
        public string SourceUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sourceExtraUrl")]
        public string SourceExtraUrl { get; set; }

    }
}
