// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ModelRequest
    {
        /// <summary>
        /// Initializes a new instance of the ModelRequest class.
        /// </summary>
        public ModelRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ModelRequest class.
        /// </summary>
        public ModelRequest(string name = default(string), string key = default(string), string category = default(string), int? version = default(int?), string metaInfo = default(string), string deploymentId = default(string), string tenantId = default(string))
        {
            Name = name;
            Key = key;
            Category = category;
            Version = version;
            MetaInfo = metaInfo;
            DeploymentId = deploymentId;
            TenantId = tenantId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public int? Version { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "metaInfo")]
        public string MetaInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deploymentId")]
        public string DeploymentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public string TenantId { get; set; }

    }
}
