// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProcessInstanceActionRequest
    {
        /// <summary>
        /// Initializes a new instance of the ProcessInstanceActionRequest
        /// class.
        /// </summary>
        public ProcessInstanceActionRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProcessInstanceActionRequest
        /// class.
        /// </summary>
        public ProcessInstanceActionRequest(string action = default(string))
        {
            Action = action;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "action")]
        public string Action { get; set; }

    }
}
