// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ProcessInstanceResponse
    {
        /// <summary>
        /// Initializes a new instance of the ProcessInstanceResponse class.
        /// </summary>
        public ProcessInstanceResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProcessInstanceResponse class.
        /// </summary>
        public ProcessInstanceResponse(string id = default(string), string url = default(string), string businessKey = default(string), bool? suspended = default(bool?), bool? ended = default(bool?), string processDefinitionId = default(string), string processDefinitionUrl = default(string), string processDefinitionKey = default(string), string activityId = default(string), IList<RestVariable> variables = default(IList<RestVariable>), string tenantId = default(string), string name = default(string), bool? completed = default(bool?))
        {
            Id = id;
            Url = url;
            BusinessKey = businessKey;
            Suspended = suspended;
            Ended = ended;
            ProcessDefinitionId = processDefinitionId;
            ProcessDefinitionUrl = processDefinitionUrl;
            ProcessDefinitionKey = processDefinitionKey;
            ActivityId = activityId;
            Variables = variables;
            TenantId = tenantId;
            Name = name;
            Completed = completed;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "businessKey")]
        public string BusinessKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "suspended")]
        public bool? Suspended { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ended")]
        public bool? Ended { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processDefinitionId")]
        public string ProcessDefinitionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processDefinitionUrl")]
        public string ProcessDefinitionUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processDefinitionKey")]
        public string ProcessDefinitionKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "activityId")]
        public string ActivityId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "variables")]
        public IList<RestVariable> Variables { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public string TenantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "completed")]
        public bool? Completed { get; set; }

    }
}
