// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ProcessInstanceCreateRequest
    {
        /// <summary>
        /// Initializes a new instance of the ProcessInstanceCreateRequest
        /// class.
        /// </summary>
        public ProcessInstanceCreateRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProcessInstanceCreateRequest
        /// class.
        /// </summary>
        public ProcessInstanceCreateRequest(string processDefinitionId = default(string), string processDefinitionKey = default(string), string message = default(string), string businessKey = default(string), IList<RestVariable> variables = default(IList<RestVariable>), IList<RestVariable> transientVariables = default(IList<RestVariable>), string tenantId = default(string), bool? returnVariables = default(bool?))
        {
            ProcessDefinitionId = processDefinitionId;
            ProcessDefinitionKey = processDefinitionKey;
            Message = message;
            BusinessKey = businessKey;
            Variables = variables;
            TransientVariables = transientVariables;
            TenantId = tenantId;
            ReturnVariables = returnVariables;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processDefinitionId")]
        public string ProcessDefinitionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processDefinitionKey")]
        public string ProcessDefinitionKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "businessKey")]
        public string BusinessKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "variables")]
        public IList<RestVariable> Variables { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transientVariables")]
        public IList<RestVariable> TransientVariables { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public string TenantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "returnVariables")]
        public bool? ReturnVariables { get; set; }

    }
}
