// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProcessEngineInfoResponse
    {
        /// <summary>
        /// Initializes a new instance of the ProcessEngineInfoResponse class.
        /// </summary>
        public ProcessEngineInfoResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProcessEngineInfoResponse class.
        /// </summary>
        public ProcessEngineInfoResponse(string name = default(string), string resourceUrl = default(string), string exception = default(string), string version = default(string))
        {
            Name = name;
            ResourceUrl = resourceUrl;
            Exception = exception;
            Version = version;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resourceUrl")]
        public string ResourceUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exception")]
        public string Exception { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public string Version { get; set; }

    }
}
