// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ProcessInstanceQueryRequest
    {
        /// <summary>
        /// Initializes a new instance of the ProcessInstanceQueryRequest
        /// class.
        /// </summary>
        public ProcessInstanceQueryRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProcessInstanceQueryRequest
        /// class.
        /// </summary>
        public ProcessInstanceQueryRequest(int? start = default(int?), int? size = default(int?), string sort = default(string), string order = default(string), string processInstanceId = default(string), string processBusinessKey = default(string), string processDefinitionId = default(string), string processDefinitionKey = default(string), string superProcessInstanceId = default(string), string subProcessInstanceId = default(string), bool? excludeSubprocesses = default(bool?), string involvedUser = default(string), bool? suspended = default(bool?), bool? includeProcessVariables = default(bool?), IList<QueryVariable> variables = default(IList<QueryVariable>), string tenantId = default(string), string tenantIdLike = default(string), bool? withoutTenantId = default(bool?))
        {
            Start = start;
            Size = size;
            Sort = sort;
            Order = order;
            ProcessInstanceId = processInstanceId;
            ProcessBusinessKey = processBusinessKey;
            ProcessDefinitionId = processDefinitionId;
            ProcessDefinitionKey = processDefinitionKey;
            SuperProcessInstanceId = superProcessInstanceId;
            SubProcessInstanceId = subProcessInstanceId;
            ExcludeSubprocesses = excludeSubprocesses;
            InvolvedUser = involvedUser;
            Suspended = suspended;
            IncludeProcessVariables = includeProcessVariables;
            Variables = variables;
            TenantId = tenantId;
            TenantIdLike = tenantIdLike;
            WithoutTenantId = withoutTenantId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start")]
        public int? Start { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "size")]
        public int? Size { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sort")]
        public string Sort { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "order")]
        public string Order { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processInstanceId")]
        public string ProcessInstanceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processBusinessKey")]
        public string ProcessBusinessKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processDefinitionId")]
        public string ProcessDefinitionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processDefinitionKey")]
        public string ProcessDefinitionKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "superProcessInstanceId")]
        public string SuperProcessInstanceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subProcessInstanceId")]
        public string SubProcessInstanceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "excludeSubprocesses")]
        public bool? ExcludeSubprocesses { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "involvedUser")]
        public string InvolvedUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "suspended")]
        public bool? Suspended { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "includeProcessVariables")]
        public bool? IncludeProcessVariables { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "variables")]
        public IList<QueryVariable> Variables { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public string TenantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantIdLike")]
        public string TenantIdLike { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "withoutTenantId")]
        public bool? WithoutTenantId { get; set; }

    }
}
