// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class QueryVariable
    {
        /// <summary>
        /// Initializes a new instance of the QueryVariable class.
        /// </summary>
        public QueryVariable()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryVariable class.
        /// </summary>
        /// <param name="variableOperation">Possible values include: 'EQUALS',
        /// 'NOT_EQUALS', 'EQUALS_IGNORE_CASE', 'NOT_EQUALS_IGNORE_CASE',
        /// 'LIKE', 'LIKE_IGNORE_CASE', 'GREATER_THAN',
        /// 'GREATER_THAN_OR_EQUALS', 'LESS_THAN',
        /// 'LESS_THAN_OR_EQUALS'</param>
        public QueryVariable(string name = default(string), string operation = default(string), object value = default(object), string type = default(string), string variableOperation = default(string))
        {
            Name = name;
            Operation = operation;
            Value = value;
            Type = type;
            VariableOperation = variableOperation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operation")]
        public string Operation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public object Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'EQUALS', 'NOT_EQUALS',
        /// 'EQUALS_IGNORE_CASE', 'NOT_EQUALS_IGNORE_CASE', 'LIKE',
        /// 'LIKE_IGNORE_CASE', 'GREATER_THAN', 'GREATER_THAN_OR_EQUALS',
        /// 'LESS_THAN', 'LESS_THAN_OR_EQUALS'
        /// </summary>
        [JsonProperty(PropertyName = "variableOperation")]
        public string VariableOperation { get; set; }

    }
}
