// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SubmitFormRequest
    {
        /// <summary>
        /// Initializes a new instance of the SubmitFormRequest class.
        /// </summary>
        public SubmitFormRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubmitFormRequest class.
        /// </summary>
        public SubmitFormRequest(string action = default(string), string processDefinitionId = default(string), string taskId = default(string), string businessKey = default(string), IList<RestFormProperty> properties = default(IList<RestFormProperty>))
        {
            Action = action;
            ProcessDefinitionId = processDefinitionId;
            TaskId = taskId;
            BusinessKey = businessKey;
            Properties = properties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "action")]
        public string Action { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processDefinitionId")]
        public string ProcessDefinitionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "taskId")]
        public string TaskId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "businessKey")]
        public string BusinessKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IList<RestFormProperty> Properties { get; set; }

    }
}
