// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TableResponse
    {
        /// <summary>
        /// Initializes a new instance of the TableResponse class.
        /// </summary>
        public TableResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TableResponse class.
        /// </summary>
        public TableResponse(string name = default(string), string url = default(string), long? count = default(long?))
        {
            Name = name;
            Url = url;
            Count = count;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public long? Count { get; set; }

    }
}
