// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TableMetaData
    {
        /// <summary>
        /// Initializes a new instance of the TableMetaData class.
        /// </summary>
        public TableMetaData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TableMetaData class.
        /// </summary>
        public TableMetaData(string tableName = default(string), IList<string> columnNames = default(IList<string>), IList<string> columnTypes = default(IList<string>))
        {
            TableName = tableName;
            ColumnNames = columnNames;
            ColumnTypes = columnTypes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tableName")]
        public string TableName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "columnNames")]
        public IList<string> ColumnNames { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "columnTypes")]
        public IList<string> ColumnTypes { get; set; }

    }
}
