// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TaskRequest
    {
        /// <summary>
        /// Initializes a new instance of the TaskRequest class.
        /// </summary>
        public TaskRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TaskRequest class.
        /// </summary>
        public TaskRequest(string owner = default(string), string assignee = default(string), string delegationState = default(string), string name = default(string), string description = default(string), System.DateTime? dueDate = default(System.DateTime?), int? priority = default(int?), string parentTaskId = default(string), string category = default(string), string tenantId = default(string), string formKey = default(string), bool? ownerSet = default(bool?), bool? assigneeSet = default(bool?), bool? delegationStateSet = default(bool?), bool? nameSet = default(bool?), bool? descriptionSet = default(bool?), bool? duedateSet = default(bool?), bool? prioritySet = default(bool?), bool? parentTaskIdSet = default(bool?), bool? categorySet = default(bool?), bool? tenantIdSet = default(bool?), bool? formKeySet = default(bool?))
        {
            Owner = owner;
            Assignee = assignee;
            DelegationState = delegationState;
            Name = name;
            Description = description;
            DueDate = dueDate;
            Priority = priority;
            ParentTaskId = parentTaskId;
            Category = category;
            TenantId = tenantId;
            FormKey = formKey;
            OwnerSet = ownerSet;
            AssigneeSet = assigneeSet;
            DelegationStateSet = delegationStateSet;
            NameSet = nameSet;
            DescriptionSet = descriptionSet;
            DuedateSet = duedateSet;
            PrioritySet = prioritySet;
            ParentTaskIdSet = parentTaskIdSet;
            CategorySet = categorySet;
            TenantIdSet = tenantIdSet;
            FormKeySet = formKeySet;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "owner")]
        public string Owner { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assignee")]
        public string Assignee { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "delegationState")]
        public string DelegationState { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dueDate")]
        public System.DateTime? DueDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "priority")]
        public int? Priority { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentTaskId")]
        public string ParentTaskId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public string TenantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "formKey")]
        public string FormKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ownerSet")]
        public bool? OwnerSet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assigneeSet")]
        public bool? AssigneeSet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "delegationStateSet")]
        public bool? DelegationStateSet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nameSet")]
        public bool? NameSet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "descriptionSet")]
        public bool? DescriptionSet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "duedateSet")]
        public bool? DuedateSet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "prioritySet")]
        public bool? PrioritySet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentTaskIdSet")]
        public bool? ParentTaskIdSet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categorySet")]
        public bool? CategorySet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantIdSet")]
        public bool? TenantIdSet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "formKeySet")]
        public bool? FormKeySet { get; set; }

    }
}
