// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Activiti.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UserInfoResponse
    {
        /// <summary>
        /// Initializes a new instance of the UserInfoResponse class.
        /// </summary>
        public UserInfoResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UserInfoResponse class.
        /// </summary>
        public UserInfoResponse(string key = default(string), string value = default(string), string url = default(string))
        {
            Key = key;
            Value = value;
            Url = url;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

    }
}
